### PR TITLE
Fixes missing config files.

### LINKED ISSUE #39: Error on configuration generation
So, I tried to compile a fresh JAR and started the bot in an empty directory.

First, the bot stopped because of the missing `bot.properties` file. This is fine, I created the file and filled the token.

Then, I started the bot once again and this time I got an error because the config files were missing. The bot was suppose to generate them but the generation is not working. Here is an example of a stack trace I got:
```
Exception in thread "main" java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1034)
        at io.slama.core.ConfigKt.createPresenceFile(config.kt:123)
        at io.slama.core.ConfigKt.getPresenceConfig(config.kt:179)
        at io.slama.UGEBot.<init>(main.kt:44)
        at io.slama.MainKt.main(main.kt:127)
        at io.slama.MainKt.main(main.kt)
```

I think generating a file in a directory not existing is a problem.

### PR DESCRIPTION
**Pull request by notKamui**
Closes #39

### CODE REVIEW

File: src/main/kotlin/io/slama/main.kt [hunk 1]
```diff
@@ -124,5 +125,6 @@ class UGEBot(token: String) : ListenerAdapter() {
 }
 
 fun main() {
+    configSetup()
```
Comment (SlamaFR) [inline src/main/kotlin/io/slama/main.kt:127]: There is a little problem. This method should create the potentially missing `bot.properties` file. The issue is that this file is required by the line 34.

**Review by SlamaFR — CHANGES_REQUESTED** [review]
Little problem spotted

**Review by SlamaFR — APPROVED** [review]
