### PR TITLE
Fix broken AutoRole discrimination

### LINKED ISSUE #82: AutoRole discrimination fails with names starting the same way
If you create two AutoRoles, saying `AutoRole` and `AutoRole2`. 

Now, if you click on a button of the second one, the bot will trigger both. This is due to this line:
```kt
override fun onButtonClick(event: ButtonClickEvent) {
    if (!event.componentId.startsWith(name)) return
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    val guild = event.guild ?: return
    if (guild.id != guildId) return
    ...
}
```

We should use a unique ID just like calls.

### PR DESCRIPTION
**Pull request by SlamaFR**
Resolves #82

### CODE REVIEW

File: src/main/kotlin/io/slama/events/autoroles.kt [hunk 1]
```diff
@@ -55,12 +57,16 @@ class AutoRole(
     }
 
     override fun onButtonClick(event: ButtonClickEvent) {
-        if (!event.componentId.startsWith(name)) return
+        val matchResult = buttonIdRegex.find(event.componentId) ?: return
+
+        val name = matchResult.groupValues[1]
```
Comment (notKamui) [inline src/main/kotlin/io/slama/events/autoroles.kt]: use MatchResult::destructured (property) to expect clear groups

```kt
val (name, index) = matchResult.destructured.let { (name, index) -> name to index.toInt() }
```

this will produce a much better stacktrace if something goes wrong at some point

**Review by notKamui — CHANGES_REQUESTED** [review]

File: src/main/kotlin/io/slama/events/autoroles.kt (hunk 1 above)
Comment (SlamaFR) [reply src/main/kotlin/io/slama/events/autoroles.kt]: Oh! I found the `destructured` thing but didn't find a nice solution to convert second group to Integer.

**Review by notKamui — APPROVED** [review]
