### PR TITLE
Config rework, full reload, and missing folders

### LINKED ISSUE #51: `reload` command is not reloading everything
At the moment, shusher config and presence config are not reloaded by the `reload` command.

### LINKED ISSUE #52: File creation is not handled on fail
If a call or a poll file fails to create, because the destination path is not found for example, the bot throws an exception instead of handling the error and sending a friendly message to the user.

### PR DESCRIPTION
**Pull request by notKamui**
- The configuration engine has been completely reworked and rendered opaque. This implies better control over it, and better safety.
- Reload is now complete (guilds, presence, shusher) with the local commands `reload` or `reset` (they do the exact same thing)
- If the user has the marvelous idea of deleting folders while the application is running, it will automatically reset the configuration (and thus create new folders).

### CODE REVIEW

**Comment by notKamui** [comment]
Closes #51

**Comment by notKamui** [comment]
Closes #52

File: src/main/kotlin/io/slama/core/config.kt [hunk 1]
```diff
@@ -25,40 +24,197 @@ object ConfigFolders {
     const val GUILD_CONFIG_ROOT = "${CONFIG_ROOT}guilds/"
 }
 
-private val guildConfigs: MutableMap<Long, GuildConfig> = mutableMapOf()
+class BotConfiguration private constructor() {
```
Comment (SlamaFR) [inline src/main/kotlin/io/slama/core/config.kt:27]: I would name this just `Configuration`

File: src/main/kotlin/io/slama/events/shusher.kt [hunk 2]
```diff
@@ -24,7 +24,7 @@ class Shusher(
 
     private val roles = mutableMapOf<String, String>()
     private val random = Random(System.currentTimeMillis())
-    private val config = getShusherConfig()
+    private val config = BotConfiguration.shusher
```
Comment (SlamaFR) [inline src/main/kotlin/io/slama/events/shusher.kt]: I'm not sure but this a reference or a value copy? Because I think that if we reload the config, the shusher keeps doing with the config it already has.

File: src/main/kotlin/io/slama/main.kt [hunk 3]
```diff
@@ -37,7 +40,7 @@ class UGEBot(token: String) : ListenerAdapter() {
         .enableIntents(GatewayIntent.GUILD_MEMBERS)
         .build()
 
-    private val presenceConfig = getPresenceConfig()
+    private val presenceConfig = BotConfiguration.presence
```
Comment (SlamaFR) [inline src/main/kotlin/io/slama/main.kt]: Same as for the shusher

**Review by SlamaFR — APPROVED** [review]
