### PR TITLE
Fix duplicated AutoRoles on reload

### LINKED ISSUE #9: Duplicate AutoRole listening on reload
**Bug description :**
If the bot is reloaded, AutoRoles are reacting twice (or more depending on total reloads since initial boot), throwing exceptions in logs.

**Steps to reproduce:**
1. Start the bot
2. Trigger an AutoRole (should work fine)
3. Remove the given role
4. Reload the bot
5. Trigger once again the AutoRole

An exception is thrown stating that the interaction has already been acknowledged.

### PR DESCRIPTION
**Pull request by SlamaFR**
This closes #9

### CODE REVIEW

File: src/main/kotlin/io/slama/events/autoroles.kt [hunk 1]
```diff
@@ -103,5 +103,10 @@ fun Guild.loadAutoRoles() {
 }
 
 fun clearAutoRoles() {
+    autoRoles.values.forEach { autoRoles ->
```
Comment (notKamui) [inline src/main/kotlin/io/slama/events/autoroles.kt]: autoRoles.values could be flattened to avoid the nested forEach

**Review by notKamui — CHANGES_REQUESTED** [review]

**Review by notKamui — APPROVED** [review]
